flesh out logging logic

diff --git a/src/Misc/layoutroot/run-helper.sh.template b/src/Misc/layoutroot/run-helper.sh.template
--- a/src/Misc/layoutroot/run-helper.sh.template
+++ b/src/Misc/layoutroot/run-helper.sh.template
@@ -32,9 +32,15 @@ if [ ! -z "$RUNNER_WAIT_FOR_DOCKER_IN_SECONDS" ]; then
             "$DIR"/safe_sleep.sh 1
         done
     fi
-    if [[ ! -z "$RUNNER_WAIT_FOR_DOCKER_EXIT_ON_FAILURE" && $RUNNER_WAIT_FOR_DOCKER_SUCCESS == false ]]; then
-        echo "Docker is not ready, exiting..."
-        exit 1
+    if [[ $RUNNER_WAIT_FOR_DOCKER_SUCCESS == false ]]; then
+        echo "Docker is not ready after $RUNNER_WAIT_FOR_DOCKER_IN_SECONDS seconds"
+
+        if [[ $RUNNER_WAIT_FOR_DOCKER_EXIT_ON_FAILURE == true ]]; then
+            echo "Respecting RUNNER_WAIT_FOR_DOCKER_EXIT_ON_FAILURE, exiting..."
+            exit 1
+        else
+            echo "RUNNER_WAIT_FOR_DOCKER_EXIT_ON_FAILURE not true, continuing anyways..."
+        fi
     fi
 fi
 
