readabilty and a small bugfix, now it is final and tested; the previous reasoning of catching a non zero exit code with  the second launchctl call was wrong, . Now the first one will fail on a non zero exit code.

diff --git a/src/Misc/layoutbin/darwin.svc.sh.template b/src/Misc/layoutbin/darwin.svc.sh.template
--- a/src/Misc/layoutbin/darwin.svc.sh.template
+++ b/src/Misc/layoutbin/darwin.svc.sh.template
@@ -87,7 +87,11 @@ function start()
 function stop()
 {
     echo "stopping ${SVC_NAME}"
-    (! launchctl unload -S Background  "${PLIST_PATH}" 2>&1 | grep -q 'Could not find specified service') || (echo "there was a problem when unloading from the Background context trying to unload from the Aqua context instead"; launchctl unload "${PLIST_PATH}") || (echo "unload from Aqua context failed as well"; failed "failed to unload ${PLIST_PATH}")
+    STDERR_OUT=$(launchctl unload -S Background  "${PLIST_PATH}" 2>&1 || failed "failed to unload ${PLIST_PATH}" )
+    if  grep -q 'Could not find specified service' <<< "$STDERR_OUT" ; then
+        echo "there was a problem when unloading from the Background context trying to unload from the Aqua context instead"
+        launchctl unload "${PLIST_PATH}" || (echo "unload from Aqua context failed as well"; failed "failed to unload ${PLIST_PATH}")
+    fi
     status
 }
 
