Improve error handling for config and unconfig agent. (#189)
* Improve error handling for config and unconfig agent.
Print friendly message when config or unconfig is not run as an admin.

* address code review comments

diff --git a/src/Misc/layoutbin/darwin.svc.sh.template b/src/Misc/layoutbin/darwin.svc.sh.template
--- a/src/Misc/layoutbin/darwin.svc.sh.template
+++ b/src/Misc/layoutbin/darwin.svc.sh.template
@@ -43,28 +43,28 @@ function install()
     fi
 
     if [ -f "${TEMP_PATH}" ]; then
-      rm "${TEMP_PATH}"
+      rm "${TEMP_PATH}" || failed "failed to delete ${TEMP_PATH}"
     fi
 
     log_path="${HOME}/Library/Logs/${SVC_NAME}"
     echo "Creating ${log_path}"
-    mkdir -p "${log_path}"
-    chown ${SUDO_UID:-$UID}:${SUDO_GID} "${log_path}"
+    mkdir -p "${log_path}" || failed "failed to create ${log_path}"
+    chown ${SUDO_UID:-$UID}:${SUDO_GID} "${log_path}" || failed "failed to set permissions for ${log_path}"
 
     echo Creating ${PLIST_PATH}
     sed "s/{{User}}/${SUDO_USER:-$USER}/g; s/{{SvcName}}/$SVC_NAME/g; s@{{AgentRoot}}@${AGENT_ROOT}@g; s@{{UserHome}}@$HOME@g;" "${TEMPLATE_PATH}" > "${TEMP_PATH}" || failed "failed to create replacement temp file"
-    cp "${TEMP_PATH}" "${PLIST_PATH}" || "failed to copy plist"
-    chown ${SUDO_UID:-$UID}:${SUDO_GID} "${PLIST_PATH}"
+    mv "${TEMP_PATH}" "${PLIST_PATH}" || failed "failed to copy plist"
+    chown ${SUDO_UID:-$UID}:${SUDO_GID} "${PLIST_PATH}" || failed "failed to set owner for ${PLIST_PATH}"
 
     # Since we started with sudo, runsvc.sh will be owned by root. Change this to current login user.
     echo Creating runsvc.sh    
-    cp ./bin/runsvc.sh ./runsvc.sh
-    chown ${SUDO_UID:-$UID}:${SUDO_GID} ./runsvc.sh
-    chmod 755 ./runsvc.sh
+    cp ./bin/runsvc.sh ./runsvc.sh || failed "failed to copy runsvc.sh"
+    chown ${SUDO_UID:-$UID}:${SUDO_GID} ./runsvc.sh || failed "failed to set owner for runsvc.sh"
+    chmod 755 ./runsvc.sh || failed "failed to set permission for runsvc.sh"
 
     echo Creating ${CONFIG_PATH}
-    echo "${PLIST_PATH}" > ${CONFIG_PATH}
-    chown ${SUDO_UID:-$UID}:${SUDO_GID} ${CONFIG_PATH}
+    echo "${PLIST_PATH}" > ${CONFIG_PATH} || failed "failed to create .Service file"
+    chown ${SUDO_UID:-$UID}:${SUDO_GID} ${CONFIG_PATH} || failed "failed to set permission for ${CONFIG_PATH}"
 
     echo "svc install complete"
 }
@@ -72,14 +72,14 @@ function install()
 function start()
 {
     echo "starting ${SVC_NAME}"
-    sudo -u "${SUDO_USER}" launchctl load -w "${PLIST_PATH}" || "failed to load ${PLIST_PATH}"
+    sudo -u "${SUDO_USER}" launchctl load -w "${PLIST_PATH}" || failed "failed to load ${PLIST_PATH}"
     status
 }
 
 function stop()
 {
     echo "stopping ${SVC_NAME}"
-    sudo -u "${SUDO_USER}" launchctl unload "${PLIST_PATH}" || "failed to unload ${PLIST_PATH}"
+    sudo -u "${SUDO_USER}" launchctl unload "${PLIST_PATH}" || failed "failed to unload ${PLIST_PATH}"
     status
 }
 
@@ -87,9 +87,9 @@ function uninstall()
 {
     echo "uninstalling ${SVC_NAME}"
     stop
-    rm "${PLIST_PATH}"
+    rm "${PLIST_PATH}" || failed "failed to delete ${PLIST_PATH}"
     if [ -f "${CONFIG_PATH}" ]; then
-      rm "${CONFIG_PATH}"
+      rm "${CONFIG_PATH}" || failed "failed to delete ${CONFIG_PATH}"
     fi
 }
 
@@ -103,7 +103,7 @@ function status()
         echo
         echo "not installed"
         echo
-        exit
+        return
     fi
 
     echo
@@ -132,8 +132,7 @@ case $SVC_CMD in
    "uninstall") uninstall;;
    "start") start;;
    "stop") stop;;
-   "status") status;;
    *) usage;;
 esac
 
-
+exit 0
diff --git a/src/Misc/layoutbin/systemd.svc.sh.template b/src/Misc/layoutbin/systemd.svc.sh.template
--- a/src/Misc/layoutbin/systemd.svc.sh.template
+++ b/src/Misc/layoutbin/systemd.svc.sh.template
@@ -22,6 +22,12 @@ if [ ! -f "${TEMPLATE_PATH}" ]; then
     failed "Must run from agent root or install is corrupt"
 fi
 
+#check if we run as root
+if [[ $(id -u) != "0" ]]; then
+    echo "Failed: This script requires to run with sudo." >&2
+    exit 1
+fi
+
 function install()
 {
     echo "Creating launch agent in ${UNIT_PATH}"
@@ -30,47 +36,48 @@ function install()
     fi
 
     if [ -f "${TEMP_PATH}" ]; then
-      rm "${TEMP_PATH}"
+      rm "${TEMP_PATH}" || failed "failed to delete ${TEMP_PATH}"
     fi
 
     sed "s/{{User}}/${SUDO_USER:-$USER}/g; s/{{Description}}/$(echo ${SVC_DESCRIPTION} | sed -e 's/[\/&]/\\&/g')/g; s/{{AgentRoot}}/$(echo ${AGENT_ROOT} | sed -e 's/[\/&]/\\&/g')/g;" "${TEMPLATE_PATH}" > "${TEMP_PATH}" || failed "failed to create replacement temp file"
-    cp "${TEMP_PATH}" "${UNIT_PATH}" || "failed to copy unit file"
+    mv "${TEMP_PATH}" "${UNIT_PATH}" || failed "failed to copy unit file"
     
     # unit file should not be executable and world writable
-    chmod 664 ${UNIT_PATH}
-    systemctl daemon-reload
+    chmod 664 ${UNIT_PATH} || failed "failed to set permissions on ${UNIT_PATH}"
+    systemctl daemon-reload || failed "failed to reload daemons"
     
 	# Since we started with sudo, runsvc.sh will be owned by root. Change this to current login user.    
-    cp ./bin/runsvc.sh ./runsvc.sh
-    chown ${SUDO_UID:-$UID}:${SUDO_GID} ./runsvc.sh
-    chmod 755 ./runsvc.sh
+    cp ./bin/runsvc.sh ./runsvc.sh || failed "failed to copy runsvc.sh"
+    chown ${SUDO_UID:-$UID}:${SUDO_GID} ./runsvc.sh || failed "failed to set owner for runsvc.sh"
+    chmod 755 ./runsvc.sh || failed "failed to set permission for runsvc.sh"
 
-    systemctl enable ${SVC_NAME} || "failed to enable ${SVC_NAME}"
+    systemctl enable ${SVC_NAME} || failed "failed to enable ${SVC_NAME}"
 
-    echo "${SVC_NAME}" > ${CONFIG_PATH}
+    echo "${SVC_NAME}" > ${CONFIG_PATH} || failed "failed to create .Service file"
+    chown ${SUDO_UID:-$UID}:${SUDO_GID} ${CONFIG_PATH} || failed "failed to set permission for ${CONFIG_PATH}"
 }
 
 function start()
 {
-    systemctl start ${SVC_NAME} || "failed to start ${SVC_NAME}"
+    systemctl start ${SVC_NAME} || failed "failed to start ${SVC_NAME}"
     status    
 }
 
 function stop()
 {
-    systemctl stop ${SVC_NAME} || "failed to stop ${SVC_NAME}"    
+    systemctl stop ${SVC_NAME} || failed "failed to stop ${SVC_NAME}"    
     status
 }
 
 function uninstall()
 {
     stop
-    systemctl disable ${SVC_NAME} || "failed to enable ${SVC_NAME}"
-    rm "${UNIT_PATH}"
+    systemctl disable ${SVC_NAME} || failed "failed to enable ${SVC_NAME}"
+    rm "${UNIT_PATH}" || failed "failed to delete ${UNIT_PATH}"
     if [ -f "${CONFIG_PATH}" ]; then
-      rm "${CONFIG_PATH}"
+      rm "${CONFIG_PATH}" || failed "failed to delete ${CONFIG_PATH}"
     fi
-    systemctl daemon-reload
+    systemctl daemon-reload || failed "failed to reload daemons"
 }
 
 function status()
@@ -82,7 +89,7 @@ function status()
         echo
         echo "not installed"
         echo
-        exit
+        return
     fi
 
     systemctl status ${SVC_NAME}
@@ -106,3 +113,4 @@ case $SVC_CMD in
    *) usage;;
 esac
 
+exit 0
